name = "Zahra Nasr"
license = "MIT"
licenselink = "https://github.com/Zahra-Nasr/zahranasr.netlify.app/blob/master/LICENSE.md"
description = "Have a nice day"
homepage = "https://github.com/Zahra-Nasr/zahranasr.netlify.app"
min_version = "0.84"
tags = ["widgets",
        "resume",
        "portfolio",
        "responsive",
        "clean",
        "personal",
        "company",
        "blog",
        "minimal",
        "light",
        "dark",
        "multilingual",
        "documentation",
        "landing page",
        "projects",
        "single page",
        "contact form",
        "mobile",
        "gallery",
        "search",
        "presentation",
        "simple",
        "minimalist",
        "starter",
        "modern",
        "one page",
        "customizable",
        "technical",
        "product",
        "slide"
        ]
features = ["page builder", "widgets", "themes", "search", "research publication system", "filterable portfolio",
            "blog", "create courses", "talks", "events", "slides", "gallery", "contact form"]

[author]
  name = "Zahra Nasr"
  homepage = "https://zahranasr.netlify.app"

